#!/usr/bin/env python

import numpy as np
from peakdet import Physio

import physioqc.metrics.cardiac as cardiac
import physioqc.metrics.utils as utils

samplerate, starttime, columns, data, compression, columnsource = utils.readbidstsv(
    "testdata/sub-007_ses-05_task-rest_run-01_physio.tsv.gz", colspec="cardiac"
)

rawcard = Physio(np.nan_to_num(data.flatten()), fs=samplerate)

print(rawcard.data)
print(rawcard.data.shape)

cardiaclist = cardiac.cardiacsqi(rawcard, debug=True)
cardiac.plotheartbeatqualities(cardiaclist, totaltime=(len(rawcard.data) / samplerate))
cardiac.plotcardiacwaveformwithquality(rawcard, cardiaclist, samplerate)
cardiac.summarizeheartbeats(cardiaclist)
